remote_theme: just-the-docs/just-the-docs

title: HJPARK
description: My development docs
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hidingke8982.github.io"

# Aux links for the upper right navigation
aux_links:
  "On GitHub":
    - "https://github.com/hidingke8982/hidingke8982.github.io"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true                                                            # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/hidingke8982/hidingke8982.github.io"  # the github URL for your repo

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: dark